### ISSUE TITLE
minimal working OTA sample?

### ISSUE THREAD

**Issue by thomas725** [taunusflieger/anemometer#12]
Hey there!

I'm currently trying to switch an ESP32 project of mine from Arduino to Rust because the Arduino software I've written get's sluggish over time and sometimes crashes, I suspect it has memory leaks.

Important feature I need is OTA, which seems is much more difficult with Rust than on Arduino, and your project is the first I've found that seems to have figured that one out. Sadly your project looks overwhelmingly big to my eyes, so I wanted to ask if you maybe could help me reach a minimal working OTA sample.

Thank you,
kind regards,
Thomas

**Comment by taunusflieger** [comment]
Hi Thomas,the core OTA functionality is not much. Take a look at https://github.com/taunusflieger/anemometer/blob/master/anemometer-production/src/task/ota.rs
This where the fw download and the flashing happens.

**Comment by taunusflieger** [comment]
.
